# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache:
  packages: true
  directories:
  - _bookdown_files
  - $HOME/.npm

before_install:
- nvm install stable
- npm install netlify-cli -g

script:
- Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::gitbook')"
- Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::pdf_book')"
- Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::epub_book')"

deploy:
  provider: script
  script: netlify deploy --prod --dir docs
  skip_cleanup: true
